FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/tsconfig.json ./
COPY --from=build /app/tsconfig.node.json ./
COPY --from=build /app/vite.config.ts ./
COPY --from=build /app/package*.json ./
COPY --from=build /app/.eslintrc.cjs ./
COPY --from=build /app/node_modules ./node_modules

CMD ["npm", "run", "preview"]