---
apiVersion: v1
kind: Namespace
metadata:
  name: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: client
  name: deployment-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: client
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
    spec:
      containers:
      - image: 939218795127.dkr.ecr.ap-southeast-1.amazonaws.com/client:lastest
        imagePullPolicy: Always
        name: client
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: client
  name: service-client
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: client