steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-f'
      - Dockerfile
      - '-t'
      - 'gcr.io/bangkok-bank-test/service:latest'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/bangkok-bank-test/service:latest'
    id: Push
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-southeast1
      - CLOUDSDK_CONTAINER_CLUSTER=bangkok-bank-test-cluster
    args:
      - apply
      - '-f'
      - gcp/kubernetes.yaml
    id: Deploy
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-southeast1
      - CLOUDSDK_CONTAINER_CLUSTER=bangkok-bank-test-cluster
    args:
      - rollout
      - restart
      - deployment
      - service
    id: Restart
